const CREDIT_CARDS = [
    // ============================
    // ENTRY LEVEL (15K - 40K salary)
    // ============================
    {
        id: "sbi-cashback",
        name: "SBI Cashback Credit Card",
        bank: "SBI Card",
        tier: "entry",
        joiningFee: 0,
        annualFee: 999,
        feeWaiver: "Waived on 2L annual spend",
        minSalary: 25000,
        minSpend: 10000,
        rewardRate: "5% cashback on online (capped Rs.2,000/mo), 1% offline (capped Rs.2,000/mo)",
        rewardDetails: "5% cashback on online spends capped at Rs.2,000/month. 1% cashback on offline capped at Rs.2,000/month. Total monthly cap Rs.4,000. Excludes gaming, toll, and government payments. (Devalued April 2026)",
        lounge: "Domestic: 4/year via RuPay network",
        fuelWaiver: "1% surcharge waiver up to Rs.500/month",
        forexMarkup: "3.5% + GST",
        welcomeBenefit: "None",
        milestoneBenefits: "2,000 bonus cashback on 1L spend in a year, 2,000 more at 2L",
        bestFor: ["online", "cashback"],
        highlights: [
            { text: "5% cashback on online spends — no merchant restriction", type: "good" },
            { text: "Best entry-level cashback card per Aly Hajiani & Sharan", type: "good" },
            { text: "DEVALUED Apr 2026: Monthly cap Rs.4,000 (was Rs.5,000/cycle)", type: "warn" },
            { text: "Excludes gaming, toll, govt payments. Points redeemable in multiples of 4,000 only", type: "warn" }
        ],
        applyUrl: "https://www.sbicard.com/en/personal/credit-cards/cashback/sbi-card-cashback.page",
        eligibility: "Min age 21, salaried with 25K+ monthly income, CIBIL 700+",
        howToApply: "Apply via SBI Card website, Paisabazaar, or visit nearest SBI branch. Salary account holders at SBI get faster approval.",
        creatorTip: "Aly Hajiani rates this the #1 low-cost card. Finance With Sharan recommends it as a starter card for anyone earning 25K+."
    },
    {
        id: "amazon-icici",
        name: "Amazon Pay ICICI Credit Card",
        bank: "ICICI Bank",
        tier: "entry",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Lifetime Free",
        minSalary: 15000,
        minSpend: 5000,
        rewardRate: "5% on Amazon (Prime), 2% on Amazon (non-Prime), 1% elsewhere",
        rewardDetails: "5% back on Amazon with Prime membership. 2% on Amazon without Prime. 1% on all other spends. Rewards as Amazon Pay balance.",
        lounge: "None",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "3.5% + GST",
        welcomeBenefit: "Rs.500 Amazon voucher on approval",
        milestoneBenefits: "None",
        bestFor: ["online", "cashback"],
        highlights: [
            { text: "Lifetime free — zero annual or joining fee ever", type: "good" },
            { text: "5% back on Amazon is among the highest for any card", type: "good" },
            { text: "Rewards only as Amazon Pay balance, not cash", type: "warn" },
            { text: "Ideal first credit card for beginners", type: "info" }
        ],
        applyUrl: "https://www.amazon.in/amazonpay/icici-credit-card",
        eligibility: "Min age 21, income 15K+/month, CIBIL 700+. Apply only via Amazon app/website.",
        howToApply: "Open Amazon app > Amazon Pay > Apply for Credit Card. ICICI salary account holders get instant approval. Cannot apply via bank branch.",
        creatorTip: "Every creator recommends this as a must-have free card. Aly Hajiani calls it the best no-brainer card in India."
    },
    {
        id: "sbi-simplyclick",
        name: "SBI SimplyCLICK Credit Card",
        bank: "SBI Card",
        tier: "entry",
        joiningFee: 499,
        annualFee: 499,
        feeWaiver: "Waived on 1L annual spend",
        minSalary: 20000,
        minSpend: 8000,
        rewardRate: "10x on partners, 5x on all online, 1x offline",
        rewardDetails: "10 reward points per Rs.100 on SBI partners (Amazon, Swiggy, BookMyShow etc). 5 points per Rs.100 on other online. 1 point per Rs.100 offline.",
        lounge: "None",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "3.5% + GST",
        welcomeBenefit: "Rs.500 Amazon voucher",
        milestoneBenefits: "Rs.2,000 e-voucher on Rs.1L spend, Rs.2,000 more on Rs.2L spend",
        bestFor: ["online", "rewards"],
        highlights: [
            { text: "10x rewards on partner brands (Amazon, Swiggy, BookMyShow)", type: "good" },
            { text: "Very easy fee waiver at just Rs.1L annual spend", type: "good" },
            { text: "Good for young professionals starting out", type: "info" },
            { text: "Points value is low at ~0.25 paisa each", type: "warn" }
        ],
        applyUrl: "https://www.sbicard.com/en/personal/credit-cards/shopping/simplyclick-sbi-card.page",
        eligibility: "Min age 21, salaried 20K+/month, CIBIL 700+",
        howToApply: "Apply via SBI Card website, Paisabazaar, or BankBazaar. Pre-approved offers available in SBI net banking.",
        creatorTip: "Good secondary card for online shopping. Stack with Amazon ICICI for maximum online rewards."
    },
    {
        id: "idfc-first-classic",
        name: "IDFC FIRST Classic Credit Card",
        bank: "IDFC FIRST Bank",
        tier: "entry",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Lifetime Free",
        minSalary: 15000,
        minSpend: 5000,
        rewardRate: "Up to 10x reward points, 0.25% base reward",
        rewardDetails: "10x reward points on select categories. 6x on all other spends. Points never expire. Low base value but versatile.",
        lounge: "None",
        fuelWaiver: "1% fuel surcharge waiver",
        forexMarkup: "3.5%",
        welcomeBenefit: "Rs.500 welcome voucher (terms apply)",
        milestoneBenefits: "Monthly milestone offers on spends",
        bestFor: ["cashback", "rewards"],
        highlights: [
            { text: "Lifetime free with no hidden charges", type: "good" },
            { text: "Reward points never expire", type: "good" },
            { text: "Easy approval for first-time card applicants", type: "info" },
            { text: "DEVALUED 2026: LTF earn rate worsened by ~25%", type: "warn" }
        ],
        applyUrl: "https://www.idfcfirstbank.com/credit-card/classic",
        eligibility: "Min age 21, income 15K+/month, CIBIL 680+",
        howToApply: "Apply via IDFC FIRST Bank app or website. Very high approval rate for new-to-credit applicants.",
        creatorTip: "Recommended by 1% Club as a starter card. NOTE: IDFC FIRST devalued LTF cards in 2026 — earn rate down 25%. Amazon Pay ICICI is now a stronger free alternative."
    },
    {
        id: "federal-scapia",
        name: "Scapia Credit Card",
        bank: "Federal Bank",
        tier: "entry",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Lifetime Free",
        minSalary: 20000,
        minSpend: 10000,
        rewardRate: "2% reward rate on all spends as travel credits",
        rewardDetails: "Flat 2% back as Scapia coins on all transactions. Coins redeemable for flights and hotels on Scapia app at 1:1 value.",
        lounge: "4 domestic lounge visits/quarter via Visa",
        fuelWaiver: "1% fuel surcharge waiver",
        forexMarkup: "0% forex markup — best in class",
        welcomeBenefit: "None",
        milestoneBenefits: "Occasional bonus coin campaigns",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "ZERO forex markup — best for international spends", type: "good" },
            { text: "Free lounge access — rare for a LTF card", type: "good" },
            { text: "2% reward rate on everything with no caps", type: "good" },
            { text: "Coins only redeemable on Scapia app for travel", type: "warn" }
        ],
        applyUrl: "https://www.scapia.app",
        eligibility: "Min age 21, income 20K+/month, decent CIBIL score",
        howToApply: "Download Scapia app and apply. Fully digital process. Card issued by Federal Bank.",
        creatorTip: "Aly Hajiani's top pick for LTF travel card. CardExpert rates it best for zero forex. Perfect for international travelers."
    },
    {
        id: "hsbc-liveplus",
        name: "HSBC Live+ Credit Card",
        bank: "HSBC",
        tier: "entry",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Lifetime Free",
        minSalary: 25000,
        minSpend: 10000,
        rewardRate: "10% on dining/grocery (max Rs.1,000/mo), 1.5% on rest",
        rewardDetails: "10% cashback on dining and grocery (capped at Rs.1,000 per month). 1.5% unlimited cashback on all other spends. Best metro card for food lovers.",
        lounge: "None",
        fuelWaiver: "None",
        forexMarkup: "3.5%",
        welcomeBenefit: "None",
        milestoneBenefits: "None",
        bestFor: ["dining", "cashback"],
        highlights: [
            { text: "10% cashback on dining & grocery — highest in category", type: "good" },
            { text: "1.5% unlimited cashback on everything else", type: "good" },
            { text: "Lifetime free — no fee ever", type: "good" },
            { text: "Dining cashback capped at Rs.1,000/month", type: "warn" }
        ],
        applyUrl: "https://www.hsbc.co.in/credit-cards/products/live-plus/",
        eligibility: "Min age 21, income 25K+/month, metro cities preferred (Mumbai, Delhi, Bangalore, etc.)",
        howToApply: "Apply via HSBC website. HSBC account not mandatory but helps. Available in major metro cities.",
        creatorTip: "CardExpert calls this the best grocery/dining card in India. Perfect complement to SBI Cashback for a powerful 2-card combo."
    },
    // ============================
    // MID RANGE (40K - 75K salary)
    // ============================
    {
        id: "hdfc-swiggy-blck",
        name: "HDFC Swiggy BLCK Credit Card",
        bank: "HDFC Bank",
        tier: "mid",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Lifetime Free (limited period offer)",
        minSalary: 40000,
        minSpend: 15000,
        rewardRate: "10% on Swiggy (min Rs.249/txn), 5% on online, 1% on offline",
        rewardDetails: "10% cashback on Swiggy ecosystem — NEW Apr 17 2026: minimum Rs.249 per transaction required for 10%, below that earns 5% or 1%. Cashback now adjusted within same billing cycle. New Cleartrip benefit: 5% cashback (capped Rs.1,500) + 6% instant flight discount.",
        lounge: "4 domestic lounge visits/quarter",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "2% + GST",
        welcomeBenefit: "Swiggy One membership",
        milestoneBenefits: "Bonus Swiggy credits on milestone spends",
        bestFor: ["dining", "online"],
        highlights: [
            { text: "10% back on Swiggy + 5% on all online spends", type: "good" },
            { text: "NEW Apr 2026: Cleartrip 5% cashback (Rs.1,500 cap) added", type: "good" },
            { text: "Currently lifetime free — grab before offer ends", type: "good" },
            { text: "NEW Apr 17 2026: Need Rs.249+ per transaction for 10% rate", type: "warn" }
        ],
        applyUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/swiggy-hdfc-bank-credit-card",
        eligibility: "Min age 21, income 40K+/month, CIBIL 720+",
        howToApply: "Apply via HDFC Bank website, Swiggy app, or pre-approved in HDFC NetBanking. HDFC salary holders get priority.",
        creatorTip: "Aly Hajiani recommends for Swiggy heavy users. 1% Club says this is the best free food delivery card available now."
    },
    {
        id: "axis-ace",
        name: "Axis Bank ACE Credit Card",
        bank: "Axis Bank",
        tier: "mid",
        joiningFee: 499,
        annualFee: 499,
        feeWaiver: "Waived on Rs.2L annual spend",
        minSalary: 40000,
        minSpend: 15000,
        rewardRate: "5% on bills & recharges, 4% on Swiggy/Zomato, 2% on all others",
        rewardDetails: "5% cashback on utility bills and recharges via Google Pay. 4% on Swiggy & Zomato. 2% cashback on everything else. All cashback as Google Pay credits.",
        lounge: "None",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "3.5% + GST",
        welcomeBenefit: "None",
        milestoneBenefits: "None",
        bestFor: ["cashback", "online"],
        highlights: [
            { text: "2% cashback on ALL spends — rare flat rate", type: "good" },
            { text: "5% on bill payments via Google Pay", type: "good" },
            { text: "One of the best all-rounder cashback cards", type: "info" },
            { text: "Cashback only via Google Pay credits", type: "warn" }
        ],
        applyUrl: "https://www.axisbank.com/retail/cards/credit-card/ace-credit-card",
        eligibility: "Min age 21, income 40K+/month, CIBIL 720+",
        howToApply: "Apply via Axis Bank website or Google Pay app. Easiest approval via Google Pay for existing users.",
        creatorTip: "Reward Points Club and Aly Hajiani both highlight this as the best flat cashback card. Note: Axis capped rewards on insurance/utility bills from Apr 2026."
    },
    {
        id: "indusind-tiger",
        name: "IndusInd Tiger Credit Card",
        bank: "IndusInd Bank",
        tier: "mid",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Lifetime Free",
        minSalary: 35000,
        minSpend: 10000,
        rewardRate: "1.5% reward rate, 2 free movie tickets/month",
        rewardDetails: "1.5 reward points per Rs.100 spent. 2 free movie tickets per month on BookMyShow (up to Rs.500). Domestic + international lounge access.",
        lounge: "Lounge access now spend-linked from Apr 2026: Rs.1.5L/quarter required for standard cards",
        fuelWaiver: "1% fuel surcharge waiver",
        forexMarkup: "1.8% — one of the lowest",
        welcomeBenefit: "None",
        milestoneBenefits: "None",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "1.8% forex markup — among the lowest available", type: "good" },
            { text: "2 free movie tickets/month on BookMyShow", type: "good" },
            { text: "DEVALUED Apr 2026: Lounge access now requires Rs.1.5L quarterly spend", type: "warn" },
            { text: "Base reward rate is average at 1.5%", type: "info" }
        ],
        applyUrl: "https://www.indusind.com/in/en/personal/cards/credit-card.html",
        eligibility: "Min age 21, income 35K+/month, CIBIL 700+",
        howToApply: "Apply via IndusInd Bank website or visit branch. Online application takes 5-7 days.",
        creatorTip: "Aly Hajiani previously called this best LTF for intl travel. Apr 2026 lounge devaluation (effective April 1) makes it less attractive — Scapia now better for free lounge access."
    },
    {
        id: "bob-eterna",
        name: "BOB Eterna Credit Card",
        bank: "Bank of Baroda",
        tier: "mid",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Lifetime Free (limited offer)",
        minSalary: 50000,
        minSpend: 20000,
        rewardRate: "Up to 3.75% cashback on online spends",
        rewardDetails: "3.75% cashback on online spends up to Rs.40K/month. 1% on offline spends. Very competitive for a free card.",
        lounge: "4 domestic + 2 international lounge visits per quarter",
        fuelWaiver: "1% fuel surcharge waiver",
        forexMarkup: "2.5%",
        welcomeBenefit: "1,000 bonus reward points",
        milestoneBenefits: "Additional lounge visits on higher spends",
        bestFor: ["online", "cashback"],
        highlights: [
            { text: "3.75% cashback on online — among highest for free cards", type: "good" },
            { text: "Both domestic and international lounge access", type: "good" },
            { text: "Currently lifetime free", type: "good" },
            { text: "NEW Apr 2026: 1% fee on education, toll >Rs.5K, railway >Rs.30K payments", type: "warn" }
        ],
        applyUrl: "https://www.bankofbaroda.in/personal-banking/digital-products/cards/credit-card",
        eligibility: "Min age 21, income 50K+/month, CIBIL 720+",
        howToApply: "Apply via Bank of Baroda website. BOB salary account holders get priority and instant offers.",
        creatorTip: "CardExpert's sleeper pick. Still great value but Apr 2026 added fees on education/toll/railway payments. Scapia (Federal Bank) is exempt from these charges."
    },
    {
        id: "axis-indigo",
        name: "IndiGo Axis Bank Credit Card",
        bank: "Axis Bank",
        tier: "mid",
        joiningFee: 799,
        annualFee: 799,
        feeWaiver: "Waived on Rs.2L annual spend",
        minSalary: 40000,
        minSpend: 15000,
        rewardRate: "Accelerated BluChip miles on IndiGo + bonus on dining, grocery & UPI",
        rewardDetails: "Earns IndiGo BluChip miles on all spends. Accelerated miles on IndiGo.com flight bookings. Bonus rewards on grocery, dining, and UPI transactions. BluChip miles redeemable for IndiGo tickets and upgrades.",
        lounge: "Domestic lounge access included per quarter",
        fuelWaiver: "1% fuel surcharge waiver",
        forexMarkup: "3.5%",
        welcomeBenefit: "Bonus BluChip miles on first IndiGo booking with the card",
        milestoneBenefits: "Bonus miles on annual IndiGo spend milestones",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "NEW Feb 2026: First dedicated IndiGo co-branded card by Axis Bank", type: "good" },
            { text: "Accelerated BluChip miles on every IndiGo flight booking", type: "good" },
            { text: "Bonus rewards on grocery, dining & UPI — useful for everyday spends", type: "info" },
            { text: "Best value only for frequent IndiGo flyers (4+ flights/year)", type: "warn" }
        ],
        applyUrl: "https://www.axisbank.com/retail/cards/credit-card",
        eligibility: "Min age 21, income 40K+/month, CIBIL 720+",
        howToApply: "Apply via Axis Bank website or IndiGo official booking channels.",
        creatorTip: "Best airline co-brand for IndiGo loyalists launched in 2026. The BluChip integration accelerates miles on every booking. Pair with Axis ACE for non-IndiGo everyday spends."
    },
    // ============================
    // PREMIUM (75K - 2L salary)
    // ============================
    {
        id: "hdfc-regalia-gold",
        name: "HDFC Regalia Gold Credit Card",
        bank: "HDFC Bank",
        tier: "premium",
        joiningFee: 2500,
        annualFee: 2500,
        feeWaiver: "Waived on Rs.3L annual spend",
        minSalary: 75000,
        minSpend: 25000,
        rewardRate: "5 points per Rs.200 spent (devalued May 2026 from 4/Rs.150)",
        rewardDetails: "5 reward points per Rs.200 (was 4 per Rs.150 — ~25% devaluation from May 15, 2026). Points transferable to airline miles at 2:1 ratio. New Boarding Edge benefit: upload boarding pass for free spa/transfer perks.",
        lounge: "3 domestic/quarter (requires Rs.60K spend in prev quarter) + 6 international/year via Priority Pass. Now via digital QR/SMS vouchers.",
        fuelWaiver: "1% surcharge waiver up to Rs.1,000/month",
        forexMarkup: "2% + GST (new 1.75% DCC fee on INR international transactions)",
        welcomeBenefit: "2,500 reward points on first spend",
        milestoneBenefits: "5,000 points on Rs.3L spend, 7,500 on Rs.5L spend",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "New Boarding Edge benefit: free spa/transfers after flights", type: "good" },
            { text: "Points transferable to airline miles — great for travel", type: "good" },
            { text: "DEVALUED May 2026: Reward rate dropped ~25% (5pts/Rs.200 vs 4pts/Rs.150)", type: "warn" },
            { text: "Domestic lounge now needs Rs.60K/quarter spend (was unconditional)", type: "warn" }
        ],
        applyUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card",
        eligibility: "Min age 21, income 75K+/month or 9L+ annual, CIBIL 750+",
        howToApply: "Apply via HDFC NetBanking (check pre-approved offers first), HDFC website, or branch. HDFC salary account gives best approval odds.",
        creatorTip: "Finance With Sharan's recommended card for the 1-1.5L salary bracket. Aly Hajiani notes this is the gateway to HDFC's premium ecosystem."
    },
    {
        id: "icici-sapphiro",
        name: "ICICI Sapphiro Credit Card",
        bank: "ICICI Bank",
        tier: "premium",
        joiningFee: 3500,
        annualFee: 3500,
        feeWaiver: "Waived on Rs.4L annual spend",
        minSalary: 80000,
        minSpend: 30000,
        rewardRate: "2 points per Rs.100 spent, 4x on travel & dining",
        rewardDetails: "2 reward points per Rs.100 base. 4x accelerated on travel and dining categories. Points redeemable for flights, hotels on ICICI rewards portal.",
        lounge: "Lounge access now requires Rs.75K quarterly spend (up from Rs.35K) effective Jul 2026",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "2% + GST",
        welcomeBenefit: "Cleartrip voucher worth Rs.2,500",
        milestoneBenefits: "Bonus points on quarterly milestones",
        bestFor: ["travel", "dining"],
        highlights: [
            { text: "4x rewards on travel & dining", type: "good" },
            { text: "Still one of the best mid-premium travel cards", type: "good" },
            { text: "DEVALUED Jul 2026: Lounge needs Rs.75K/quarter spend (was Rs.35K)", type: "warn" },
            { text: "ICICI reward point value is lower than HDFC", type: "warn" }
        ],
        applyUrl: "https://www.icicibank.com/card/credit-cards/icici-bank-sapphiro-credit-card",
        eligibility: "Min age 21, income 80K+/month, CIBIL 750+",
        howToApply: "Apply via ICICI iMobile app (best for pre-approved), ICICI website, or branch. ICICI salary holders get instant offers.",
        creatorTip: "Best lounge card for the money. If you travel frequently, this card pays for itself in 2 lounge visits."
    },
    {
        id: "sbi-elite",
        name: "SBI Card ELITE",
        bank: "SBI Card",
        tier: "premium",
        joiningFee: 4999,
        annualFee: 4999,
        feeWaiver: "Waived on Rs.10L annual spend",
        minSalary: 75000,
        minSpend: 25000,
        rewardRate: "5x on dining, grocery, dept stores, movies",
        rewardDetails: "5 reward points per Rs.100 on dining, grocery, departmental stores, and movies. 1 point per Rs.100 on all other spends. Points redeemable for travel vouchers.",
        lounge: "8 domestic + 6 international lounge visits per year",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "1.99% + GST — competitive",
        welcomeBenefit: "5,000 bonus reward points",
        milestoneBenefits: "5,000 points each at Rs.2L, 4L, 6L, 8L annual spend milestones",
        bestFor: ["dining", "travel", "rewards"],
        highlights: [
            { text: "5x rewards on dining, grocery, movies — everyday categories", type: "good" },
            { text: "Low forex markup of 1.99%", type: "good" },
            { text: "Good international lounge access", type: "info" },
            { text: "Fee waiver requires Rs.10L spend — very high threshold", type: "warn" }
        ],
        applyUrl: "https://www.sbicard.com/en/personal/credit-cards/travel/sbi-card-elite.page",
        eligibility: "Min age 21, income 75K+/month or 9L+ annual, CIBIL 750+",
        howToApply: "Apply via SBI Card website, SBI bank branch, or Paisabazaar.",
        creatorTip: "Good for foodies who eat out frequently. The 5x dining rewards can offset the annual fee quickly."
    },
    {
        id: "idfc-mayura",
        name: "IDFC FIRST Mayura Credit Card",
        bank: "IDFC FIRST Bank",
        tier: "premium",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Lifetime Free (invite only)",
        minSalary: 75000,
        minSpend: 25000,
        rewardRate: "Up to 6x reward points on all categories",
        rewardDetails: "6x reward points on all categories. Points never expire. Best LTF premium card for regular spending. 0% forex markup on international transactions.",
        lounge: "4 domestic lounge visits per quarter",
        fuelWaiver: "1% fuel surcharge waiver",
        forexMarkup: "0% — zero forex markup",
        welcomeBenefit: "None (invite-based card)",
        milestoneBenefits: "Monthly milestone bonuses",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "ZERO forex markup — best for international spending", type: "good" },
            { text: "Lifetime free premium card", type: "good" },
            { text: "6x reward points on all categories", type: "good" },
            { text: "Invite-only — need existing IDFC relationship", type: "warn" }
        ],
        applyUrl: "https://www.idfcfirstbank.com/credit-card",
        eligibility: "Invite only. Need existing IDFC FIRST account with good transaction history.",
        howToApply: "Open IDFC FIRST savings account first. Use it actively for 3-6 months. Card offer appears in IDFC app automatically.",
        creatorTip: "CardExpert says zero forex makes this a must-have for international travelers. Pair with Scapia for a killer 0% forex combo."
    },
    {
        id: "amex-mrcc",
        name: "Amex Membership Rewards Credit Card",
        bank: "American Express",
        tier: "premium",
        joiningFee: 1000,
        annualFee: 4500,
        feeWaiver: "Waived on Rs.1.5L annual spend",
        minSalary: 60000,
        minSpend: 15000,
        rewardRate: "5-7% return on Amex Travel, Taj vouchers",
        rewardDetails: "1 MR point per Rs.50 spent. 1,000 bonus points on Rs.20K monthly spend. Points transfer to airline miles (Marriott, Singapore Airlines, British Airways). Best value via Taj vouchers (5-7% return).",
        lounge: "4 domestic lounge visits per year",
        fuelWaiver: "None",
        forexMarkup: "3.5% + GST",
        welcomeBenefit: "4,000 bonus MR points on first spend of Rs.5,000",
        milestoneBenefits: "1,000 MR points on Rs.20K spend each month (can earn 12,000 bonus/year)",
        bestFor: ["travel", "rewards", "dining"],
        highlights: [
            { text: "5-7% return when redeemed for Taj vouchers", type: "good" },
            { text: "Points transfer to airline/hotel partners", type: "good" },
            { text: "Amex offers portal gives additional 5-20% back", type: "info" },
            { text: "DEVALUED Jul 1 2026: Etihad Guest removed as transfer partner (transfer by Jun 30)", type: "warn" }
        ],
        applyUrl: "https://www.americanexpress.com/in/credit-cards/membership-rewards-credit-card/",
        eligibility: "Min age 21, income 60K+/month, CIBIL 750+",
        howToApply: "Apply via Amex website directly. Also get referral links from existing Amex cardholders for bonus points.",
        creatorTip: "Aly Hajiani's favorite for travel redemptions. Taj voucher hack still gives 5-7% return. URGENT: Amex removing Etihad as transfer partner Jul 1, 2026 — transfer points before Jun 30. Professor Cardz also reports a 50% back offer on MR points (limited time)."
    },
    {
        id: "hdfc-tata-neu-infinity",
        name: "HDFC Tata Neu Infinity Credit Card",
        bank: "HDFC Bank",
        tier: "premium",
        joiningFee: 1499,
        annualFee: 1499,
        feeWaiver: "Waived on Rs.2L annual spend",
        minSalary: 60000,
        minSpend: 20000,
        rewardRate: "5% on Tata brands, 1.5% on UPI, 1% on all else",
        rewardDetails: "5% NeuCoins on all Tata brands (BigBasket, Croma, AirAsia, Taj, 1mg etc). 1.5% on UPI payments. 1% on all other spends. NeuCoins = Rs.1 each.",
        lounge: "4 domestic lounge visits per quarter",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "2.5%",
        welcomeBenefit: "500 NeuCoins on first transaction",
        milestoneBenefits: "1,000 NeuCoins at Rs.2L spend",
        bestFor: ["online", "cashback"],
        highlights: [
            { text: "5% back on entire Tata ecosystem — huge brand portfolio", type: "good" },
            { text: "1.5% on UPI — one of few cards rewarding UPI spends", type: "good" },
            { text: "NeuCoins have 1:1 Rs value — easy to understand", type: "info" },
            { text: "Rewards locked to Tata Neu ecosystem", type: "warn" }
        ],
        applyUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/tata-neu-hdfc-bank-credit-card",
        eligibility: "Min age 21, income 60K+/month, CIBIL 720+",
        howToApply: "Apply via Tata Neu app or HDFC Bank website. Pre-approved offers visible in HDFC NetBanking.",
        creatorTip: "Best card for UPI spenders per CardExpert. If you use BigBasket, Croma, or book Taj hotels — this is a no-brainer."
    },
    // ============================
    // SUPER PREMIUM (2L - 5L salary)
    // ============================
    {
        id: "hdfc-diners-black",
        name: "HDFC Diners Club Black Credit Card",
        bank: "HDFC Bank",
        tier: "super",
        joiningFee: 10000,
        annualFee: 10000,
        feeWaiver: "Waived on Rs.5L annual spend",
        minSalary: 175000,
        minSpend: 50000,
        rewardRate: "3.33% reward rate across all spends",
        rewardDetails: "5 reward points per Rs.150 spent on all categories. Points worth ~Rs.1 each when redeemed for flights/hotels. One of the highest flat reward rates for any card.",
        lounge: "Unlimited domestic + international lounge access (700+ lounges)",
        fuelWaiver: "1% surcharge waiver up to Rs.1,000",
        forexMarkup: "2% + GST",
        welcomeBenefit: "5,000 bonus reward points",
        milestoneBenefits: "5,000 points at Rs.3L, 5L, 8L annual spend",
        bestFor: ["travel", "rewards", "dining"],
        highlights: [
            { text: "3.33% reward rate on ALL spends — among best in India", type: "good" },
            { text: "Unlimited lounge access globally — 700+ lounges", type: "good" },
            { text: "Golf privileges + premium dining discounts", type: "info" },
            { text: "Diners network acceptance limited at some offline stores", type: "warn" }
        ],
        applyUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-club-black",
        eligibility: "Min income Rs.1.75L/month or Rs.21L annual, CIBIL 750+",
        howToApply: "Check pre-approved offers in HDFC NetBanking first. Apply via HDFC website or visit branch. HDFC salary holders and existing premium card users get priority.",
        creatorTip: "All 4 creators rate this among India's top 3 cards. Aly Hajiani says the reward rate is unmatched at this fee level."
    },
    {
        id: "sc-ultimate",
        name: "Standard Chartered Ultimate Credit Card",
        bank: "Standard Chartered",
        tier: "super",
        joiningFee: 5000,
        annualFee: 5000,
        feeWaiver: "Waived on Rs.4L annual spend",
        minSalary: 200000,
        minSpend: 40000,
        rewardRate: "3.3% on nearly all spends",
        rewardDetails: "5 reward points per Rs.150 spent. Points redeemable for ITC, Titan, Starbucks, Fabindia vouchers at excellent value. Very versatile redemption catalog.",
        lounge: "Unlimited domestic lounge access + Priority Pass for international",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "2% + GST",
        welcomeBenefit: "5,000 reward points on first transaction",
        milestoneBenefits: "Quarterly milestone bonuses",
        bestFor: ["rewards", "travel"],
        highlights: [
            { text: "3.3% flat reward rate — matches HDFC Diners Black", type: "good" },
            { text: "Versatile redemption: ITC, Titan, Starbucks vouchers", type: "good" },
            { text: "Lower fee than Diners Black with similar rewards", type: "info" },
            { text: "May 2026: Federal Bank acquired Standard Chartered India card portfolio — cards valid, future issuance may change", type: "warn" }
        ],
        applyUrl: "https://www.sc.com/in/credit-cards/ultimate/",
        eligibility: "Min income Rs.2L/month, CIBIL 750+",
        howToApply: "Apply via SC website or branch. SC salary holders get pre-approved offers.",
        creatorTip: "CardExpert rates the redemption catalog as one of the best. Good alternative to HDFC Diners if you prefer Visa acceptance. NOTE: Federal Bank acquired SC India's card portfolio (May 4, 2026) — verify card availability before applying."
    },
    {
        id: "yes-marquee",
        name: "Yes Bank Marquee Credit Card",
        bank: "Yes Bank",
        tier: "super",
        joiningFee: 5000,
        annualFee: 5000,
        feeWaiver: "Waived on Rs.5L annual spend",
        minSalary: 200000,
        minSpend: 40000,
        rewardRate: "4.5% on online, 2% on offline",
        rewardDetails: "4.5% reward rate on online spends. 2% on offline. Points redeemable for Amazon vouchers, flights, and merchandise.",
        lounge: "8 domestic + 4 international per year",
        fuelWaiver: "1% fuel surcharge waiver",
        forexMarkup: "2% + GST",
        welcomeBenefit: "10,000 bonus reward points",
        milestoneBenefits: "5,000 points at Rs.3L, 5L annual spend",
        bestFor: ["online", "rewards"],
        highlights: [
            { text: "4.5% reward rate on online spends — highest in category", type: "good" },
            { text: "Generous welcome bonus of 10,000 points", type: "good" },
            { text: "Strong online reward rate", type: "info" },
            { text: "Yes Bank's service quality can vary", type: "warn" }
        ],
        applyUrl: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
        eligibility: "Min income Rs.2L/month, CIBIL 750+",
        howToApply: "Apply via Yes Bank website or branch.",
        creatorTip: "Good for heavy online spenders. 4.5% online rate is hard to beat at any price point."
    },
    {
        id: "equitas-selfe",
        name: "Equitas Selfe Credit Card",
        bank: "Equitas Small Finance Bank",
        tier: "premium",
        joiningFee: 999,
        annualFee: 999,
        feeWaiver: "Waived on Rs.1L spend per quarter",
        minSalary: 75000,
        minSpend: 30000,
        rewardRate: "Up to 10% in 5X categories when spending 1L+/month",
        rewardDetails: "Choose 5 accelerated categories (up to 10% back). Need Rs.1L+ monthly spend for a quarter to unlock max tier. Complimentary flight/hotel vouchers on milestones.",
        lounge: "4 domestic per quarter",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "3%",
        welcomeBenefit: "500 reward points",
        milestoneBenefits: "Flight/hotel vouchers on quarterly spend milestones",
        bestFor: ["rewards", "cashback"],
        highlights: [
            { text: "10% rewards in your chosen categories — highly customizable", type: "good" },
            { text: "Free flight/hotel vouchers on milestones", type: "good" },
            { text: "Need consistent Rs.1L/month spend to unlock max rewards", type: "warn" },
            { text: "DEVALUED Apr 2026: Complimentary insurance covers discontinued", type: "warn" }
        ],
        applyUrl: "https://www.equitasbank.com/credit-cards",
        eligibility: "Min income Rs.75K/month, CIBIL 720+",
        howToApply: "Apply via Equitas Bank website or app.",
        creatorTip: "CardExpert highlights this for power users who can consistently spend 1L+/month. The 10% in chosen categories is unmatched."
    },
    // ============================
    // HNI (5L+ salary)
    // ============================
    {
        id: "hdfc-infinia",
        name: "HDFC Infinia Credit Card",
        bank: "HDFC Bank",
        tier: "hni",
        joiningFee: 12500,
        annualFee: 12500,
        feeWaiver: "Waived on Rs.10L annual spend",
        minSalary: 500000,
        minSpend: 100000,
        rewardRate: "5 points per Rs.150 = 3.33% (higher on SmartBuy)",
        rewardDetails: "5 reward points per Rs.150 on all spends. Points worth Rs.1 each on HDFC SmartBuy flights/hotels. 10x rewards via SmartBuy portal = ~6.66% return on travel bookings.",
        lounge: "Unlimited domestic + international lounge access for primary + add-on cards",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "2% + GST",
        welcomeBenefit: "12,500 reward points",
        milestoneBenefits: "10,000 points at Rs.8L, 15,000 at Rs.15L annual spend",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "India's most aspirational credit card — gold standard for rewards", type: "good" },
            { text: "Unlimited lounge access for primary AND add-on cards", type: "good" },
            { text: "Up to 6.66% return via SmartBuy — highest in India", type: "good" },
            { text: "NEW Apr 2026: Must spend Rs.18L/yr OR Rs.50L bank relationship to retain card", type: "warn" }
        ],
        applyUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/infinia-credit-card",
        eligibility: "Invite only. Rs.5L+ monthly salary or Rs.60L+ annual ITR. NEW (Apr 2026): Must maintain Rs.18L annual spend OR Rs.50L relationship value to retain card.",
        howToApply: "Cannot apply directly. Get HDFC Diners Black first, spend heavily for 6-12 months, then request upgrade via HDFC relationship manager or NetBanking.",
        creatorTip: "Every creator's #1 aspirational card. Finance With Sharan calls it the ultimate credit card in India. Aly Hajiani warns: new Apr 2026 retention rules mean you must spend Rs.18L/year or risk downgrade."
    },
    {
        id: "axis-magnus",
        name: "Axis Bank Magnus Credit Card",
        bank: "Axis Bank",
        tier: "hni",
        joiningFee: 12500,
        annualFee: 12500,
        feeWaiver: "Waived on Rs.15L annual spend",
        minSalary: 500000,
        minSpend: 100000,
        rewardRate: ">10% on higher monthly spends (3L+/month)",
        rewardDetails: "35 EDGE points per Rs.200 spent. Bonus milestones for 1L+, 3L+, 5L+ monthly spends. Points redeemable for flights at ~10% value for high spenders.",
        lounge: "Unlimited domestic + 8 international per year",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "2% + GST",
        welcomeBenefit: "10,000 EDGE reward points",
        milestoneBenefits: "Massive milestone bonuses tied to monthly spends",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "10%+ return for heavy spenders (3L+/month)", type: "good" },
            { text: "Metal card variant available", type: "good" },
            { text: "DEVALUED 2026: Accor, Marriott, Qatar Airways removed as transfer partners", type: "warn" },
            { text: "Reward rate drops significantly below 1L/month spend", type: "warn" }
        ],
        applyUrl: "https://www.axisbank.com/retail/cards/credit-card/magnus-credit-card",
        eligibility: "Min income Rs.5L/month, relationship-based. Burgundy Private banking members get priority.",
        howToApply: "Apply via Axis Bank relationship manager or Burgundy banking. Not available via open application.",
        creatorTip: "CardExpert says this beats Infinia for high spenders. WARNING: Axis removed key transfer partners (Accor, Marriott, Qatar) in 2026 — significantly reduces travel redemption value."
    },
    {
        id: "amex-platinum",
        name: "American Express Platinum Card",
        bank: "American Express",
        tier: "hni",
        joiningFee: 60000,
        annualFee: 60000,
        feeWaiver: "No waiver — premium lifestyle card",
        minSalary: 400000,
        minSpend: 100000,
        rewardRate: "Variable — best via MR to airline miles transfers",
        rewardDetails: "1 MR point per Rs.50. Transfer to 18+ airline/hotel partners. Marriott Gold Elite status. Accor Plus membership. Value heavily depends on redemption strategy.",
        lounge: "Unlimited via Priority Pass + Centurion Lounges globally",
        fuelWaiver: "None",
        forexMarkup: "3.5% + GST",
        welcomeBenefit: "First-year signup bonus varies (typically 50,000+ MR points)",
        milestoneBenefits: "Annual hotel credit, airline credit, Uber credits",
        bestFor: ["travel", "dining"],
        highlights: [
            { text: "Centurion Lounge access — world's most exclusive lounges", type: "good" },
            { text: "Marriott Gold Elite + Accor Plus memberships included", type: "good" },
            { text: "18+ airline/hotel transfer partners globally", type: "info" },
            { text: "Rs.60K annual fee with no waiver — pure luxury play", type: "warn" }
        ],
        applyUrl: "https://www.americanexpress.com/in/credit-cards/platinum-card/",
        eligibility: "Min income Rs.4L+/month or substantial ITR. Amex reviews holistically.",
        howToApply: "Apply via Amex website. Referral from existing Platinum cardholders gives bonus MR points.",
        creatorTip: "Aly Hajiani says the first-year signup bonus alone can be worth Rs.50K+. Good value in year 1, harder to justify ongoing unless you travel luxury."
    },
    {
        id: "icici-emeralde",
        name: "ICICI Emeralde Private Credit Card",
        bank: "ICICI Bank",
        tier: "hni",
        joiningFee: 12000,
        annualFee: 12000,
        feeWaiver: "Waived on Rs.15L annual spend",
        minSalary: 500000,
        minSpend: 100000,
        rewardRate: "3% on all spends + 100% travel flexibility",
        rewardDetails: "2 reward points per Rs.100 on all spends. 100% redemption flexibility for flights and hotels via ICICI travel portal. Metal card with premium concierge.",
        lounge: "Unlimited domestic + international via Priority Pass",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "2% + GST",
        welcomeBenefit: "Metal card + premium welcome kit",
        milestoneBenefits: "Milestone bonuses at Rs.5L, 10L, 15L annual spend",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "3% flat reward rate on everything", type: "good" },
            { text: "Metal card with premium design", type: "good" },
            { text: "100% flexible travel redemption", type: "info" },
            { text: "Requires ICICI Private Banking relationship", type: "warn" }
        ],
        applyUrl: "https://www.icicibank.com/card/credit-cards",
        eligibility: "ICICI Private Banking customers. Min investment/relationship Rs.1Cr+",
        howToApply: "Available only through ICICI Private Banking relationship manager.",
        creatorTip: "For ICICI loyalists with high net worth. The metal card and concierge are best-in-class among Indian banks."
    },
    {
        id: "hsbc-premier",
        name: "HSBC Premier Credit Card",
        bank: "HSBC",
        tier: "hni",
        joiningFee: 0,
        annualFee: 0,
        feeWaiver: "Free with HSBC Premier account (min Rs.50L relationship)",
        minSalary: 400000,
        minSpend: 100000,
        rewardRate: "1:1 points transfer, accelerated travel rewards",
        rewardDetails: "2 reward points per Rs.100 on all spends. 1:1 transfer to air miles. Accelerated rewards on travel. Outstanding for frequent international travelers.",
        lounge: "Unlimited domestic + international lounge access",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "0% — zero forex markup",
        welcomeBenefit: "Depends on current offer",
        milestoneBenefits: "Quarterly milestone bonuses",
        bestFor: ["travel", "rewards"],
        highlights: [
            { text: "ZERO forex markup — best for international spending", type: "good" },
            { text: "1:1 points to air miles transfer", type: "good" },
            { text: "Lifetime free with HSBC Premier banking", type: "info" },
            { text: "Requires Rs.50L+ relationship with HSBC", type: "warn" }
        ],
        applyUrl: "https://www.hsbc.co.in/credit-cards/products/premier/",
        eligibility: "HSBC Premier account holders. Requires Rs.50L+ total relationship value.",
        howToApply: "Open HSBC Premier savings account first, then card is offered automatically.",
        creatorTip: "CardExpert rates this among the best for all-category spending at HNI level. Zero forex is a game-changer for global travelers."
    },
    // ============================
    // ADDED MAY 2026 from creator reviews
    // ============================
    {
        id: "hsbc-travelone",
        name: "HSBC TravelOne Credit Card",
        bank: "HSBC",
        tier: "premium",
        joiningFee: 4999,
        annualFee: 4999,
        feeWaiver: "Waived on Rs.4L annual spend",
        minSalary: 75000,
        minSpend: 30000,
        rewardRate: "4x points on travel/dining, 1 point per Rs.100 base, 20 transfer partners",
        rewardDetails: "1 reward point per Rs.100 base. 4x accelerated on travel and dining. Points transferable to 20 hotel/airline partners including Accor ALL (1:1 - now best value after Axis dropped Accor in Apr 2026). 1 RP = ~Re.1 via transfer partners.",
        lounge: "6 domestic + 4 international lounge visits per year via Priority Pass",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "1.99%",
        welcomeBenefit: "10,000 bonus reward points on first spend",
        milestoneBenefits: "5,000 points on Rs.4L annual spend",
        bestFor: ["travel", "rewards", "dining"],
        highlights: [
            { text: "20 transfer partners — most diverse in India", type: "good" },
            { text: "Accor 1:1 transfer now best in India (Axis dropped Accor Apr 2026)", type: "good" },
            { text: "Recommended by Aly Hajiani as Axis Atlas replacement", type: "good" },
            { text: "1.99% forex markup — very competitive for premium card", type: "good" }
        ],
        applyUrl: "https://www.hsbc.co.in/credit-cards/products/travel-one/",
        eligibility: "Min age 21, income Rs.75K+/month, CIBIL 750+. Metro cities preferred.",
        howToApply: "Apply via HSBC website. HSBC account holders get faster approval. Limited availability in tier-2 cities.",
        creatorTip: "Professor Cardz & Aly Hajiani both recommend this as the top travel card after Axis Atlas/Magnus devaluation in 2026. Accor partnership makes this unbeatable for hotel redemptions."
    },
    {
        id: "hdfc-6e-rewards-xl",
        name: "HDFC 6E Rewards XL IndiGo Credit Card",
        bank: "HDFC Bank",
        tier: "mid",
        joiningFee: 1500,
        annualFee: 1500,
        feeWaiver: "Waived on Rs.2L annual spend",
        minSalary: 40000,
        minSpend: 15000,
        rewardRate: "5% 6E Rewards on IndiGo, 3% on groceries/dining/entertainment, 1% elsewhere",
        rewardDetails: "5% 6E Rewards on IndiGo flights and add-ons (1:1 redemption). 3% accelerated on dining, groceries, entertainment. 1% on other spends. Rewards locked to IndiGo ecosystem.",
        lounge: "8 domestic lounge visits per year",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "2.5%",
        welcomeBenefit: "IndiGo flight vouchers worth Rs.3,000 + 6E Prime membership",
        milestoneBenefits: "Bonus 6E rewards on annual spend milestones",
        bestFor: ["travel", "dining"],
        highlights: [
            { text: "5% on IndiGo flights — best for IndiGo loyalists", type: "good" },
            { text: "8 domestic lounge visits/year included", type: "good" },
            { text: "Aly Hajiani verdict: worth it ONLY if you fly IndiGo monthly", type: "info" },
            { text: "Rewards locked to IndiGo — useless if you fly other airlines", type: "warn" }
        ],
        applyUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/6e-rewards-xl-indigo-hdfc-bank-credit-card",
        eligibility: "Min age 21, income Rs.40K+/month, CIBIL 720+",
        howToApply: "Apply via HDFC Bank website, IndiGo app, or visit HDFC branch.",
        creatorTip: "Aly Hajiani's May 2026 video: 'Are IndiGo Credit Cards Actually Worth It?' — his verdict: worth it only if you fly IndiGo 2x+ per month. For occasional travelers, Axis Atlas or HSBC TravelOne offer more flexibility."
    },
    {
        id: "indigo-axis-premium",
        name: "IndiGo Axis BluChip Premium Credit Card",
        bank: "Axis Bank",
        tier: "premium",
        joiningFee: 5000,
        annualFee: 5000,
        feeWaiver: "Waived on Rs.4L annual spend",
        minSalary: 75000,
        minSpend: 30000,
        rewardRate: "7% BluChips on IndiGo, 3% on travel/dining, 1% elsewhere",
        rewardDetails: "7% BluChip rewards on IndiGo flights and add-ons (1:1 redemption). 3% accelerated on travel and dining categories. 1% on other spends. NEW: Axis added IndiGo as a transfer partner in Jun 2026 — Axis Atlas/Magnus users can now transfer to BluChip.",
        lounge: "8 domestic + 4 international lounge visits per year",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "1.99%",
        welcomeBenefit: "IndiGo flight vouchers worth Rs.5,000 + 6E Prime membership",
        milestoneBenefits: "Bonus BluChips on Rs.5L, 10L annual spend",
        bestFor: ["travel", "dining"],
        highlights: [
            { text: "7% on IndiGo — highest IndiGo reward rate on any card", type: "good" },
            { text: "1.99% forex markup — beats HDFC IndiGo XL's 2.5%", type: "good" },
            { text: "Axis added IndiGo as transfer partner Jun 2026", type: "good" },
            { text: "RuPay variant available for UPI compatibility", type: "info" }
        ],
        applyUrl: "https://www.axisbank.com/retail/cards/credit-card",
        eligibility: "Min age 21, income Rs.75K+/month, CIBIL 750+",
        howToApply: "Apply via Axis Bank website, IndiGo app, or branch. Launched Feb 2026. RuPay or Visa network selectable.",
        creatorTip: "Professor Cardz Jun 2026: Axis adding IndiGo as transfer partner is partial recovery from earlier devaluations (Accor/Marriott/Qatar dropped). 7% on IndiGo is now the highest in market."
    },
    {
        id: "pnb-kiwi",
        name: "PNB Kiwi RuPay Credit Card",
        bank: "Punjab National Bank",
        tier: "entry",
        joiningFee: 0,
        annualFee: 750,
        feeWaiver: "Waived on Rs.1.5L annual spend",
        minSalary: 20000,
        minSpend: 8000,
        rewardRate: "Up to 1.5% cashback on UPI scan-and-pay, 0.5% on online",
        rewardDetails: "1.5% cashback on UPI scan-and-pay transactions. 0.5% on online card spends. 1% fuel surcharge waiver. Fully digital virtual card via Kiwi app. RuPay = works on UPI everywhere including small kirana stores.",
        lounge: "None",
        fuelWaiver: "1% surcharge waiver",
        forexMarkup: "3.5%",
        welcomeBenefit: "Rs.250 Amazon voucher (varies)",
        milestoneBenefits: "None",
        bestFor: ["cashback", "online"],
        highlights: [
            { text: "NEW Apr 22 2026 launch — PNB joins Kiwi UPI platform", type: "good" },
            { text: "1.5% UPI cashback — same as Yes Bank Kiwi", type: "good" },
            { text: "Reaches PNB's 180M customer base — easier approval", type: "info" },
            { text: "Rs.750 annual fee (waivable) despite some 'LTF' marketing claims", type: "warn" }
        ],
        applyUrl: "https://gokiwi.in/",
        eligibility: "Min age 21, income Rs.20K+/month. PNB account preferred but not required.",
        howToApply: "Download Kiwi app and apply. Virtual card issued instantly. PNB account holders get faster approval.",
        creatorTip: "Professor Cardz Jun 2026: 'Don't Miss This! PNB Joins Kiwi for UPI Rewards'. Good alternative to Yes Bank Kiwi if you have a PNB relationship or are new-to-credit."
    }
];
